name: flesan_approvals
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  data_repository:
    path: packages/data_repository
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  flutter_pdfview: ^1.0.0 # Asegúrate de usar la versión correcta
  path_provider: ^2.0.9   # Para obtener la ruta del directorio temporal
  flutter_cache_manager: ^3.3.0  # Opcional si quieres gestionar el almacenamiento en caché
  fluttertoast: ^8.0.9 # Añade la dependencia para los toasts.
  google_sign_in: ^6.2.2
  bloc: ^8.1.4
  dio: ^4.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  generate: true
  fonts:
    - family: 'Poppins'
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/images/login/
    - assets/images/google/
    - assets/images/general/
    - assets/images/svg/
    - assets/animations/
    - assets/animations/
    - assets/images/welcome/
    - assets/images/home/
    - assets/images/select_company/
    - assets/images/welcome_company/
    - assets/images/attached_files/
